version: '3.8'

services:
  # PostgreSQL 데이터베이스
  db:
    image: postgres:15
    container_name: equipment-management-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: equipment_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 백엔드 서버
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: equipment-management-backend
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/equipment_management
      JWT_SECRET: your_jwt_secret_key
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  # 프론트엔드 클라이언트
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: equipment-management-frontend
    restart: always
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: